### ISSUE TITLE
Interface with pviewer

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-schematic#4]
Make it easy to generate mesh files from schematics

**Comment by Karang** [comment]
An easy way to implement this is to simply have a method to paste a schematic to a prismarine-world. 
pviewer can already render prismarine-worlds

**Comment by rom1504** [comment]
this is mostly done
only the saving of mesh part merit additional reflexion, related https://github.com/PrismarineJS/prismarine-viewer/issues/83

**Comment by rom1504** [comment]
done, the meshing file part is another issue
